function fetch_info(i){
    let pfp = ["1.png", "2.png", "3.png", "4.png", "5.png", "2.png", "3.png"];
    let name = ["Cassie Underwood", "Terri Jones", "Maisie Hill", "Alan Delain", "Simon Reeves", "Shauna Davies", "Kiki Dee"];
    let job = ["CEO and Co-Founder", "COO and Co-Founder", "Head of Production", "Senior Programmer", "Programmer", "Management Assistant", "Senior 3D Artist"];
    let ainfo = ["Fave achievement at BC Games: Launching BC Games online! Fave thing about working for BC Games: The ability to get involved in projects across departments! Fave board game: Arkham Horror Fave movie: The Devils Any hidden talents: Not that I know of...", "Fave achievement at BC Games: Being there for BC Games's very first game development Fave thing about working for BC Games: Playing all the new releases! Fave board game: Twilight Struggle Fave movie: Shawshank Redemption Any hidden talents: I'm really good at Bridge and I've represented England for it!", "Fave thing about working for BC Games: Our ethos! We have a friendly approach to everything and that makes us so unique! Fave achievement at BC Games: Launching BC Games, it was my little baby! Fave board game: Codenames Fave movie: Toy Story Any hidden talents: I'm really good at climbing, I'm like a spider monkey.", "Fave achievement at BC Games: Supporting the Christmas rush every year Fave thing about working for BC Games: I honestly love all the people who work here! Fave board game: Mansions of Madness Fave movie: Silence of the Lambs Any hidden talents: I'm a cracking good artist!", "Fave thing about working for BC Games: Nice environment and team to work with Fave achievement at BC Games: Seeing Epic Landscape hit the million users mark Fave board game: Not a board game, MTG: Time Spiral Remastered Fav Movie: Treasure Planet Any hidden talents: I can do a really good shaggy impression (from Scooby Doo)", "Fave thing about working for BC Games: Feeling appreciated for the hard work we all do and all the work trips and outings we go on together! Fave achievement at BC Games: Visiting NYC Comicon! Fave board game: Ticket to Ride Nordic Fave movie: Frozen Any hidden talents: I'm an excellent knitter for someone of my age.", "Fave achievement at BC Games: Being a part of the BC Games logo creation Fave thing about working for BC Games: Working with so many creative people! Fave board game: Schythe Fave movie: What We Do In The Shadows Any hidden talents: I'm quite the archer!"];
    document.getElementById("pfp").src = pfp[i];
    document.getElementById("name").innerHTML = name[i];
    document.getElementById("job").innerHTML = job[i];
    document.getElementById("ainfo").innerHTML = ainfo[i];
  }